#
# Copyright (C) 2014 The CyanogenMod Project
#
# Copyright (C) 2016 The Mokee OpenSource Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/k3gduosctc/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/k3gduosctc/proprietary/vendor/firmware/bcm4350_V0301.0568.hcd:system/vendor/firmware/bcm4350_V0301.0568.hcd \
    vendor/samsung/k3gduosctc/proprietary/vendor/lib/libcne.so:system/vendor/lib/libcne.so \
    vendor/samsung/k3gduosctc/proprietary/vendor/lib/libcneapiclient.so:system/vendor/lib/libcneapiclient.so \
    vendor/samsung/k3gduosctc/proprietary/vendor/lib/libcneconn.so:system/vendor/lib/libcneconn.so \
    vendor/samsung/k3gduosctc/proprietary/vendor/lib/libcneqmiutils.so:system/vendor/lib/libcneqmiutils.so \
    vendor/samsung/k3gduosctc/proprietary/vendor/lib/libmasc.so:system/vendor/lib/libmasc.so \
    vendor/samsung/k3gduosctc/proprietary/vendor/lib/libNimsWrap.so:system/vendor/lib/libNimsWrap.so \
    vendor/samsung/k3gduosctc/proprietary/vendor/lib/libvendorconn.so:system/vendor/lib/libvendorconn.so \
    vendor/samsung/k3gduosctc/proprietary/vendor/lib/libwqe.so:system/vendor/lib/libwqe.so \
    vendor/samsung/k3gduosctc/proprietary/vendor/lib/libxml.so:system/vendor/lib/libxml.so \
    vendor/samsung/k3gduosctc/proprietary/etc/clatd.conf:system/etc/clatd.conf \
    vendor/samsung/k3gduosctc/proprietary/etc/gps.conf:system/etc/gps.conf \
    vendor/samsung/k3gduosctc/proprietary/etc/sap.conf:system/etc/sap.conf \
    vendor/samsung/k3gduosctc/proprietary/lib/hw/gps.default.so:system/lib/hw/gps.default.so \
    vendor/samsung/k3gduosctc/proprietary/lib/libgps.utils.so:system/lib/libgps.utils.so \
    vendor/samsung/k3gduosctc/proprietary/lib/libloc_api_v02.so:system/lib/libloc_api_v02.so \
    vendor/samsung/k3gduosctc/proprietary/lib/libloc_core.so:system/lib/libloc_core.so \
    vendor/samsung/k3gduosctc/proprietary/lib/libloc_ds_api.so:system/lib/libloc_ds_api.so \
    vendor/samsung/k3gduosctc/proprietary/lib/libloc_eng.so:system/lib/libloc_eng.so \
    vendor/samsung/k3gduosctc/proprietary/vendor/lib/hw/flp.default.so:system/vendor/lib/hw/flp.default.so \
    vendor/samsung/k3gduosctc/proprietary/vendor/lib/libgeofence.so:system/vendor/lib/libgeofence.so \
    vendor/samsung/k3gduosctc/proprietary/vendor/lib/libizat_core.so:system/vendor/lib/libizat_core.so \
    vendor/samsung/k3gduosctc/proprietary/vendor/lib/liblbs_core.so:system/vendor/lib/liblbs_core.so \
    vendor/samsung/k3gduosctc/proprietary/etc/firmware/a225_pfp.fw:system/etc/firmware/a225_pfp.fw \
    vendor/samsung/k3gduosctc/proprietary/etc/firmware/a225_pm4.fw:system/etc/firmware/a225_pm4.fw \
    vendor/samsung/k3gduosctc/proprietary/etc/firmware/a225p5_pm4.fw:system/etc/firmware/a225p5_pm4.fw \
    vendor/samsung/k3gduosctc/proprietary/etc/firmware/a300_pfp.fw:system/etc/firmware/a300_pfp.fw \
    vendor/samsung/k3gduosctc/proprietary/etc/firmware/a300_pm4.fw:system/etc/firmware/a300_pm4.fw \
    vendor/samsung/k3gduosctc/proprietary/vendor/lib/liblistenhardware.so:system/vendor/lib/liblistenhardware.so \
    vendor/samsung/k3gduosctc/proprietary/vendor/lib/liblistenjni.so:system/vendor/lib/liblistenjni.so \
    vendor/samsung/k3gduosctc/proprietary/vendor/lib/liblisten.so:system/vendor/lib/liblisten.so \
    vendor/samsung/k3gduosctc/proprietary/vendor/lib/liblistensoundmodel.so:system/vendor/lib/liblistensoundmodel.so \
    vendor/samsung/k3gduosctc/proprietary/vendor/firmware/libpn547_fw.so:system/vendor/firmware/libpn547_fw.so \
    vendor/samsung/k3gduosctc/proprietary/lib/libmdmdetect.so:system/lib/libmdmdetect.so \
    vendor/samsung/k3gduosctc/proprietary/lib/libperipheral_client.so:system/lib/libperipheral_client.so \
    vendor/samsung/k3gduosctc/proprietary/vendor/lib/libconfigdb.so:system/vendor/lib/libconfigdb.so \
    vendor/samsung/k3gduosctc/proprietary/vendor/lib/libdiag.so:system/vendor/lib/libdiag.so \
    vendor/samsung/k3gduosctc/proprietary/vendor/lib/libdsi_netctrl.so:system/vendor/lib/libdsi_netctrl.so \
    vendor/samsung/k3gduosctc/proprietary/vendor/lib/libdsutils.so:system/vendor/lib/libdsutils.so \
    vendor/samsung/k3gduosctc/proprietary/vendor/lib/libidl.so:system/vendor/lib/libidl.so \
    vendor/samsung/k3gduosctc/proprietary/vendor/lib/libnetmgr.so:system/vendor/lib/libnetmgr.so \
    vendor/samsung/k3gduosctc/proprietary/vendor/lib/libqcci_legacy.so:system/vendor/lib/libqcci_legacy.so \
    vendor/samsung/k3gduosctc/proprietary/vendor/lib/libqdi.so:system/vendor/lib/libqdi.so \
    vendor/samsung/k3gduosctc/proprietary/vendor/lib/libqmi.so:system/vendor/lib/libqmi.so \
    vendor/samsung/k3gduosctc/proprietary/vendor/lib/libqmi_cci.so:system/vendor/lib/libqmi_cci.so \
    vendor/samsung/k3gduosctc/proprietary/vendor/lib/libqmi_client_qmux.so:system/vendor/lib/libqmi_client_qmux.so \
    vendor/samsung/k3gduosctc/proprietary/vendor/lib/libqmi_common_so.so:system/vendor/lib/libqmi_common_so.so \
    vendor/samsung/k3gduosctc/proprietary/vendor/lib/libqmi_csi.so:system/vendor/lib/libqmi_csi.so \
    vendor/samsung/k3gduosctc/proprietary/vendor/lib/libqmi_encdec.so:system/vendor/lib/libqmi_encdec.so \
    vendor/samsung/k3gduosctc/proprietary/vendor/lib/libqmiservices.so:system/vendor/lib/libqmiservices.so \
    vendor/samsung/k3gduosctc/proprietary/bin/efsks:system/bin/efsks \
    vendor/samsung/k3gduosctc/proprietary/bin/ks:system/bin/ks \
    vendor/samsung/k3gduosctc/proprietary/bin/qcks:system/bin/qcks \
    vendor/samsung/k3gduosctc/proprietary/bin/qmuxd:system/bin/qmuxd \
    vendor/samsung/k3gduosctc/proprietary/bin/rfs_access:system/bin/rfs_access \
    vendor/samsung/k3gduosctc/proprietary/bin/rild:system/bin/rild \
    vendor/samsung/k3gduosctc/proprietary/bin/rmt_storage:system/bin/rmt_storage \
    vendor/samsung/k3gduosctc/proprietary/lib/libreference-ril.so:system/lib/libreference-ril.so \
    vendor/samsung/k3gduosctc/proprietary/lib/libril.so:system/lib/libril.so \
    vendor/samsung/k3gduosctc/proprietary/lib/librilutils.so:system/lib/librilutils.so \
    vendor/samsung/k3gduosctc/proprietary/lib/libsec-ril.so:system/lib/libsec-ril.so \
    vendor/samsung/k3gduosctc/proprietary/lib/libsec-ril-dsds.so:system/lib/libsec-ril-dsds.so \
    vendor/samsung/k3gduosctc/proprietary/lib/libsecnativefeature.so:system/lib/libsecnativefeature.so \
    vendor/samsung/k3gduosctc/proprietary/lib/libsecril-client.so:system/lib/libsecril-client.so \
    vendor/samsung/k3gduosctc/proprietary/vendor/lib/libconfigdb.so:system/vendor/lib/libconfigdb.so \
    vendor/samsung/k3gduosctc/proprietary/vendor/lib/libril-qcril-hook-oem.so:system/vendor/lib/libril-qcril-hook-oem.so \
    vendor/samsung/k3gduosctc/proprietary/vendor/lib/libwfdcommonutils.so:system/vendor/lib/libwfdcommonutils.so \
    vendor/samsung/k3gduosctc/proprietary/vendor/lib/libwfdhdcpcp.so:system/vendor/lib/libwfdhdcpcp.so \
    vendor/samsung/k3gduosctc/proprietary/vendor/lib/libwfdmmsink.so:system/vendor/lib/libwfdmmsink.so \
    vendor/samsung/k3gduosctc/proprietary/vendor/lib/libwfdmmsrc.so:system/vendor/lib/libwfdmmsrc.so \
    vendor/samsung/k3gduosctc/proprietary/vendor/lib/libwfdmmutils.so:system/vendor/lib/libwfdmmutils.so \
    vendor/samsung/k3gduosctc/proprietary/vendor/lib/libwfdnative.so:system/vendor/lib/libwfdnative.so \
    vendor/samsung/k3gduosctc/proprietary/vendor/lib/libwfdrtsp.so:system/vendor/lib/libwfdrtsp.so \
    vendor/samsung/k3gduosctc/proprietary/vendor/lib/libwfdsm.so:system/vendor/lib/libwfdsm.so \
    vendor/samsung/k3gduosctc/proprietary/vendor/lib/libwfduibcinterface.so:system/vendor/lib/libwfduibcinterface.so \
    vendor/samsung/k3gduosctc/proprietary/vendor/lib/libwfduibcsink.so:system/vendor/lib/libwfduibcsink.so \
    vendor/samsung/k3gduosctc/proprietary/vendor/lib/libwfduibcsinkinterface.so:system/vendor/lib/libwfduibcsinkinterface.so \
    vendor/samsung/k3gduosctc/proprietary/vendor/lib/libwfduibcsrc.so:system/vendor/lib/libwfduibcsrc.so \
    vendor/samsung/k3gduosctc/proprietary/vendor/lib/libwfduibcsrcinterface.so:system/vendor/lib/libwfduibcsrcinterface.so \
    vendor/samsung/k3gduosctc/proprietary/vendor/lib/libmmwfdinterface.so:system/vendor/lib/libmmwfdinterface.so \
    vendor/samsung/k3gduosctc/proprietary/vendor/lib/libmmwfdsinkinterface.so:system/vendor/lib/libmmwfdsinkinterface.so \
    vendor/samsung/k3gduosctc/proprietary/vendor/lib/libmmwfdsrcinterface.so:system/vendor/lib/libmmwfdsrcinterface.so
